apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: git-credentials
spec:
  encryptedData:
    password: AgBJQj1TjzRh9L/JJVcK65BMvpkPAI9jybeA1Q6E3euvY5igvQbMxg9KgdrkBpUlBBhU1/bCZMlEadvqnzCfKPxMqDJsPjOJErRksMMfth9unD453cXI5wUYYEv/1IJKiCwOMDJ06Hy3OBJ8UfnaxlW0bfEBCliJ8TiftuA3bN4WKZXP2pILtqrdxqunLNyzLP64Zs8SrKEoWt/OZOk8X2ODCLRMmeVeUJPozSv+zoWE1vBYYuVLxiqKurWg5YLBMUiLPsgf99t4RxyB+8Qtuc4YY952lZQVJ0FH9rNjXV1Nh6akOjCe6B7Q2rGKnkklDXr0G9FMJBzatltJ4VIxN7aNOaei/27pHoexGSHcBO8uxMbJS9yPxULSN+FdDKS6jvu03jWeCZ7LMWGy1Ig6/iJ8kEpk47UdSt9GGPuZDRpxPCqLPSaIwADKKgqyvbdX5vXaUZGqI9Aa4Gy8Cyoa/p8ScWWCkqCNlDZBgN/PTiq8YUUVA2Ka5fKCse9x7QsKi3LLEBWccNx7RJ/PVSYwGoxNinEUZLHP289TAMlqZvGYLxqzJD+tnPVtpSZE0c5GBIW8dDwKwjY05XDguyoFMeb0Dq7dfYdHJYXSyUUeW4+3GNB4pVRFLD897a1Dmo52ULRZ4kUyxFjETA1zOezWfVNOMJhMQt/wRkOAAlUu+t/GsBU0t05g+thGbzMdn5Q3PwksjxXmbhs1E+PQIPU2FzZ/kKlW1X8xD7UqoHMU43VzoVH6QGWHuBFD
    username: AgBp+LiGsswmRAnaofrgLm0+UnkZJl86cQX4PRglWOs+0WI7A/kjdZLy8IyF+P6Z+KfZPbab5hdyWxknyLdKWPY8o/v7QWknW+dUipbeuyvpIh55P4OHxAI4F6aLBiw/hKGFeJZDhTa/X8ZsvuXC5FegTCp+iIKAzJfe+VI7MK6AKlulKgFoXUfU72KpSL/KcjH8kPrpCM0Ykkglh0F69o261bbBX9af4NRYm+nu8ZR7cqw36MFq5gy44cFPEeSew0w9jOWRi35+EjSezSBXFl5zHC2O9/QLvMLLjrEvaXiFdtJM5Jm/XMcRO8P8YgY3bayRLqn+ochfFp/CiIQCv4F8z6Tw96l/cK31WlXYYG3GtljtAage6FmuYBwJIEPzygeEsHKZEOVvc/2UD+1D3LjH/05R/WKCkqxo1+pj+MEkOpJUP52qOnc6Hh2aBqGNmKU/fydUcJRqGCb4OapsSHklB3ao8duE1oRSdn3nMoJQm4OhQZ6noxGraHg0mRY0Ba3oPL3jQCIOMrGHgkLEaTo0EO46NTkeUcm+6PdHGYLwWOwYuSzJ28W/aH984v2Xkgu6uhbakEXQauJlLyJPzYI+pPCvYArmUqw7E/l2+fb6OX/H38+4FAJoG42HKQWW5KzjMmksxyS5hzwvSHshzDCxLR6c2q/VKINA80n4sAyHcjsGHYjGw/5Zq/KY5L2/sPMUhXNHMJflvJCG
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
        tekton.dev/git-0: https://github.com
      creationTimestamp: null
      name: git-credentials
    type: kubernetes.io/basic-auth

