apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: git-credentials
spec:
  encryptedData:
    password: AgAf1s/lDVfMwdBNMWY13TKrrCC5YtgfboROozx8HbVI4So1jTIJqqvgEULyWAIAs8U2q4lQj3SLsc+BeFnRvE2M5Yk4HvgdBB6/lvDJDjKmUew5cKyv1KejQNiV7X+WnqsM2b6WzQEVU9jOGypP10+DAZBrb/vb5Cl+7b/txZSkMBtfry2W7KOTPmkyDfPii7MINymKs5pKCS5SvPK5oYcfplMPYeuzqaXeZ9kz1vEi9xT1Qt42d0f1uPb9xhsulNVRhYd9zrlMpdNx6bP8Yxcm6Uce3VbuWvxjrGlT7CcVYhdm3O0cMQums32sGoZjHLy7RXvtCJaUxzqmIRCqMyofzoCtf7js1FFXYCCpox9M1P1n+dGHME2dVqKQ0aP8Amuo7MNwVz/gusgJGvi1oSKEaSEvNqMmjELvz+x9xp+1SMA76AzHJF8eh6lfjwpdRKrg0uCsAvZGgsDAR8zCV653rRz+Xd9/VVTfZUGZiKO2HMpDWwaNO+ZBeaMd4LDushSH05Lg1qMpnAgMJ7o5ToVdM3ynFMM2CKJKpOQ4ldGsxyD7U8M6nvygJLrHBrpElyoLYhThUmVf6sXQ3kgsJJTCLKpz1NdUyfMRlzB4UxwRHB2fcjVal7lzemXuD9KptjBiH3eery/yCCKGUK3HC2mtU+YWqp4GjOycxkE0Ed0WkClhUsE55NmjMC+sPevHcR8ikAAYIgag7AJqd3Di3vtstw4L8m5ll5rrk5uYYWhPHNPsO7K/1Ky2
    username: AgBOS7gSDd7//Pe6yldJgiUkbs3R197uWpYXCv/56ue64kJ5CiofO422eVvwmA4n9nKFZtAdkr0JtOzVPCauwiRneH60Hay6qazhC/Z0lM9Yw8e88y90uyXcBSN7juZlnnpEbx9UxmY8FOCggyhYQOSbAnuw5UNYWjp2PJhEyN6fGQQHILY4S/mlOi/nBB8dH0LEU4CE1sbcCqPri+06U4bWboZUvMJaUgTpbdRLb+dpcSIq/qXJPTOh020GRrBV/AD3po4btvW3rusrxQ8/JYp2uUfPwfurFgAzz2GrjpAwNuU4gSCVXcTqmi7O9+YD2Yq7OIBt/6cuO7iKZiXBblS43wTZ8H/9Mryup737TgA5RZlgXFsD+ZBpUaK+knggM6sRC7WXSX+KffNSPfcSiLqvvyeixallXNZX/iimTCWO4lTIeQU2+0YiqEo6zfejCvwh0vxnkIlbtsscaa3tGuptccaXkKAia25dT5oEzHyBbUnC3O4HWuG8yQDgnrmnSk3+pBEQudzuBhqIOcgTiR0h0xHQ8ht78teBEVb5in3I9CHeEEQp515voJuzkDITn26TZf4Lvr3bdCSwvjM971CDdzt1wQ6bmfYxA+LS5XRAKI1TEnuUbp8g/ZsGGklB9fmT/HXwfa9W56gUwEniLBGnHNetsxYutVtvOTP27KVCqY5uX4ghVbRFfoBpKYfc+h9YeaPTpNNdpRRq
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
        tekton.dev/git-0: https://github.com
      creationTimestamp: null
      name: git-credentials
    type: kubernetes.io/basic-auth

