apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: git-credentials
spec:
  encryptedData:
    password: AgA3cVkgUR/qiKSY1BqxrCFr/xGCmU/eAbhl+aLXyMukL4Bq3RBKcZPNuByWTbU8mP1dBxTvAAOACiGMduN/PxVwzvm7B4w8ABJyc5kvTDj+rU4p6zUAdoGyR6/+kH+5hBlbeMHNKT4Vys+b3XRrSoZGIJA/kOtt3VcYOxVYfA28cQ9rmf7T4R/a0DGxIOHi1rMKA4IchlpKJSAfr3CbNvLUSvWDFMa9CcPykC09VCaax09JqnPgH/UR2BF9xUNojNcpLBvadVBGh6XRjpeiqxjoRT71khE16fTlNA0R+EXA8zBXBy7Xvp2IzvVnYZKC/AGsUP0geu8Tvgyh2Hncc2C2d1coXNaJtcPbP/v1PjnJV7xikWMGCT6YhwgK6zditmkKH0nPYeCm/INAx7fViFre5+LDhMZJIiDV+WtMgA4WzTwfH7dfW8B+eOPyvNFVjwler9cz7EGsPMVL12DZNLsZvrqC8Pc4sGUPwQLBlucCTAlBLUf3FGuWL+HhZdVwzTe/7nuYOxfR0S5rNsU6Qk0svfalZOUYQzuZZon1KgzXVOx4f5iZlec5ZwAZs5RiBopGVlMo8UnAseXHP2SfOOYyCi3Z+Vz3DciXmIX6Yf/MKhaAd4Kx1K3548PTUD5g+iByLikmR/Il30z4hV/oG9du3eH100CxZZ+yqdkpPP96BT55ToB32bCalNaKgbS8HF41Z8MMe0ENVf98BeCL5o4jNYwc9TjGQ5QQH30SFts5DgLej1E1w9y+
    username: AgCUjZC0B3ofk/yfaG7EmLzNLau6xqc5ZzqGASbtgsn6cIQ9LgYWAfQL0Uwd4R/axJ5y/MtgmDEmjk6M7IaodSlt338FpttAW7ZhdbxenlqCQUCMFPikRDUuIRxoE+xdFK81vw4jLQiVffevzbou7t/TCoFitX9ssV0gGsWXK0TzN6McvAR47Y1Z5BjGv+sIttdbmqm/DFOFny5K8mmAEsiiwGHHZC9EHrsW1sbeDCZRd7VAOJyRG27MD/QX+5MQz5DcNK4cwYJhqtBi/eMULgZOJI0f2AQlwdxMpcWwqghEQFNxXAyZcEHkOeWf7ToZRA4RC8lRYR1bCyG9jojclDAn25M6pz0TxuY/hlMJ3HlGNmw5ZxIAs12hUoXVREB2vH4e9zz9RtI+WVfzhnFuy83aTEYNjWm0tK3sILm6O+HB1UmV6iuMuw4rRVCkodihrvzWFR6Xbf7f0zXbFynsRWWhpyxaGci5MSwOXkbjF4FGAN+cb40d4WVFqHqDwVJ0X5H2C3HG57SoqSmjujnAaTSM7/dGMqGbJHXQNjmbzWgvecFLXu5t1alRbSaRMfS3AeSjyhf1uarIU4PptlzYKd0Okq9+wEhaUlAXvtUPTydDYrMLmCTynt+qh6AR7kJ6gYwS/pjqA9vF2cwJqMbr4oxI+7rSxGMgDmbk3Qz9fD7DSzteIw0XZ7/PpbP5i59IGoOZd5FwSYpTRj6n
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
        tekton.dev/git-0: https://github.com
      creationTimestamp: null
      name: git-credentials
    type: kubernetes.io/basic-auth

