apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: git-credentials
spec:
  encryptedData:
    password: AgApPefAzGYGzJLO1pGBM+xEvyn860gpupExBLv/CyHSNACklZDUYmvp1nXP6hGM+Z0H/AxPLiNoAv2DNWcoznZSFr2NWdMld2dqXPiOEXEbUlFFhtCavid8+ZRlDyGycbF1mec4xMNBjAYK2+B2wLHIB3mMXVul+SVkndHFnhu4m5zkvSYv4PbOqDFzwSveL2Wew3RrJSFbEsysfhV518ljSndU6yJwJlch7vG7SJ9ZSLpc6Dm+gmIM3Caxhr4GpURHoDRYrIZXfWQx86NecmcDRUF4qLa5IO9vizhmjJg+r7aiB+KV4ZnI/rfZO02v2l4QL1bHFGjVpFYombsBHym81WaTfJI/YLkJ5sjL7H6NBTK3QoOHvLbS8ue/yOXpMnSVXl/UQSML7UrGc3dYTnbdsNnsmjicWo0mTN0ecAHf8HpFcLfSZ/YUe+WInjaF6rOrpZO3v2ggmwRdOJVdAjFWnz3ECiWN+fTDKUYmzJvQqLa9iMipf3ZtCjw1W+/L1fCd9iQgO2O49UXvWbDc1yanIVRJswyHSDu3drjtDnhPGeI1yeZdpwx0WRH9cSQ6jpYP34psIoBaYJX0RKXVhSqRQ9B7zjI769uJ2UI1OB4WyTMs9ujUYxJxMr78mGUqKFLQFs++8dKQJ9WWot8Cvea0lbh44g9dPCoGSBzROQrYNnXVmugqmT7P0TG4nCbLIBg5Kmd+lXm7yatuMCMptHw9F8aA/PMK5wqqqAkZ/ZoGst4/nQWQg2c+
    username: AgAw70HXPyh/lvO6vSSH0witxoNwYxd0H/CL7M4rWDLzksOCxqkBY+vvH0hqex3JEQnoQ64B2Fk22TOi6ecgqNH91LXIH31N732ZC/E/c52J/1/+l9tS5Qd3/O9xdL+QbGGlPgN57bvPN4Zx8Zzt9ibpE5Vfp3KvYi2weF2Xz7DBcNRLoB9NKUxLDTlFTF+wdjBvyXlIbHhPRCsScMFwhrNiAR9GeLH+eGS36zm1psqLCSrxFf4P/xUVQD3yZ/fFciR5flXHghwKgW77/PA5Hwed4EVB8yjxtiKLN26iGK2mlK2LHpnQNdAWFEvPzz/dnLabpH5Oih3ilgnQuGwVVc3+QmMqw7zmlfQRQqb7Ar1VY5eAC2v4TIpu8PyBQLSAkvDnQc1OmAtg4qLlkYBLQ+0wJ74TFhiCHsk8oRwuU7J6DNLGWZqAD6Hjjr2FlscNROZV0ubIMwJnJO/YHlNEOBBRD6RJeWihnAa3UIcqcZ0PMG2vRfgv5zBESp/e5KDXMu7iiZEjBVaEIvGj10IgGPRg8CWpYv9BhAcDn1/623ON6LFMP3yVYZfu58a5+dQIAv055rru9oB3d6gPSdSncPTbmjNMIfoiCwuKGNydLpXtCAhGGQhl0ocB3KYOiYP/JuCtbuKQfXrKlVUrZVrJVFzknBgQMcGZmUA27dOp+lQUv8+MG3TtKPhtcvmPuUNhNReMPqarF0d3XPSD
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
        tekton.dev/git-0: https://github.com
      creationTimestamp: null
      name: git-credentials
    type: kubernetes.io/basic-auth

