apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: git-credentials
spec:
  encryptedData:
    password: AgBha28PLdJYiK+syhYHhWRN3I1dNFJ+tFqo/RJd+HirF2EQ9XLNZI1DqOq2IFVYaYQ2tRFx8PTA2e3rCynjpw6UByqHcK1YElOL2HS2egW77QNx3nZQWsFPkQ9U2y3jzta5roCgru3gQO1+EfGCz3sur6PUrIECXQWwD9xzE/k0GyZfLAQPBz9FvzvsStCkLPPjFz8f8VsIB6QAk2rjsy4/hyI7Zh7SpqW3t3BQYHzVnH23JWPeUOjcMGbLhFoFzHGrfB/Y/Db2azGK+94V13MWbrKz2Qld7a5JOgoZcCrbXY2Nj+WW3mLnB5WKrtbeWmkL9PrYAk5bgEVSiaoo75WcOaNB+idWibKBcmEVNBfDfGo/B79+xlOo73EmnbtJNBSqptbkJRPpgtDJiy5Nh41ZibDZUY7uovU4UPKfN3y8ySZF9Mbm7gKVmBkTLi8OaX4rwopigHx2+sdqRJkHmmhgnKBzyPh0J9q8NXf0Tt6kJh1XxEzSEKhf4DQcTrxVDGy9I25jrvAso95hw5fK8j3Nv6KjWsjS9ymBKw9IQyV9pZkRk0/auTBbHZUY/iipJnE0FNotxHnhLSQOKbQnN23sUgAWdvlpvJIxFr9wmWL6IhILpWV+lMdbqmh6XXb/3pF1v4Qo3OSvMuIwMlGLYp70jz51R7LerLDBjEBiptirL+flaX/JBLN+tp6bd9iQWh5r2atSMIMpKyqb/FX1fZQmatPkpth/xVsDsiB1MDsVuJoNU+SbiFXT
    username: AgBwDRpTQjnzr/sIlWTpnHP7mEGnGx+TdYjKxAHRKDUpeGAcrpVa7/k6afUDZ6emt/TNLCcLXYinyzWca2EPZ2RA2BSUgBYNPkAmukAxPN0zAdnxNoDaI6nCM6graz41Tm5iU+dwjZcFboJdJsoNAkWWOkZp6pD6/OUZ2EB8LK5eMxD77ioQnKU9Bzxl2/Wx9ZE1b2H9kgPuSYN0PPDbiNjGC7mj4D+lVQQOhIaAUE28EHalcexhYl6uWyC/BJMkiSjHa5Y2Ya57GxUryJPHnSZjENKluO05yhHtwAeFJm2EiEym21u298pM9m8JeNcpx7ethptOEHYLt8vTKG31keVGOPdLmGuVMhNa4o4f2A5UsABZyXTWxStLBrdEJZDgzjdBgIyBHa3yz0QJCxejTatCo+bMBqYC/aDql6S+jxoJ950OpWUA4uwW6mYLxm7CrZLHaOmeQMQmqqVqG6gX/d/tLlqwQkQgfJCN9Pxzaa7DwbvhgMrtzOMWHt88wWnhKVXYvY1cVc6CY3ko4/XEJ8nLlMy1cxnJh+rco7Ek+oVMvgw+1IffZliYBjHBf37xEZcomhwJkyuAu36ekw/DmCuy8IENnd/k15POAzZSBtIRSTCpLuNHRy2/VTbADH3MBOar1WYC1Sb00+MB+Cc1xUSkqN7oOmQ3WjG4IRa3GctJ99bxK3UXCN8/ap2dnxUAtUfaf6IWpTxu7Wup
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
        tekton.dev/git-0: https://github.com
      creationTimestamp: null
      name: git-credentials
    type: kubernetes.io/basic-auth

